"""
PDF report generation with SHAP and heatmap embedding.
"""
import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
import qrcode
import io
from datetime import datetime
import base64
import tempfile
from PIL import Image as PILImage
import cv2
import numpy as np
from typing import Dict, Any

from utils.explainability import generate_shap_plot

def generate_pdf_report(diagnosis_record: Dict[str, Any], diagnosis_id: str, output_dir: str) -> str:
    """
    Generate an A4 PDF report with all diagnostic information.
    """
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.join(output_dir, f'diagnosis_{diagnosis_id}.pdf')
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height-50, "Rare Disease Diagnostic Report")

    # Date and ID
    c.setFont("Helvetica", 10)
    c.drawString(50, height-70, f"Report ID: {diagnosis_id}")
    c.drawString(50, height-85, f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")

    # Symptoms
    y = height-120
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Patient Symptoms")
    y -= 15
    c.setFont("Helvetica", 10)
    symptoms_text = ', '.join(diagnosis_record['symptoms'])
    c.drawString(70, y, symptoms_text)

    # Demographics
    y -= 25
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Demographics")
    y -= 15
    c.setFont("Helvetica", 10)
    demo = diagnosis_record['demographics']
    demo_text = f"Age: {demo.get('age','N/A')}, Gender: {demo.get('gender','N/A')}, Ethnicity: {demo.get('ethnicity','N/A')}, Region: {demo.get('region','N/A')}"
    c.drawString(70, y, demo_text)

    # Top5 results
    y -= 30
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Top 5 Differential Diagnoses")
    y -= 20
    data = [['Rank', 'Disease', 'Confidence']]
    for i, (disease, conf) in enumerate(diagnosis_record['final_top5'], 1):
        data.append([str(i), disease, f"{conf:.2%}"])
    table = Table(data, colWidths=[50, 300, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    table.wrapOn(c, width, height)
    table.drawOn(c, 50, y - (len(data)*20))
    y -= (len(data)*20 + 30)

    # Risk and urgency
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, f"Risk Level: {diagnosis_record['risk_level']}")
    y -= 15
    c.setFont("Helvetica", 10)
    c.drawString(50, y, f"Urgency: {diagnosis_record['urgency']}")
    y -= 30

    # SHAP explanation
    if diagnosis_record.get('shap_values') and diagnosis_record.get('shap_explanations'):
        shap_img_b64 = generate_shap_plot(
            np.array(diagnosis_record['shap_values']),
            [s for s, _ in diagnosis_record['shap_explanations']],  # feature names
            [d for d, _ in diagnosis_record['final_top5']],  # class names (just for title)
            idx=0
        )
        shap_img = base64.b64decode(shap_img_b64)
        shap_io = io.BytesIO(shap_img)
        c.drawImage(ImageReader(shap_io), 50, y-150, width=400, height=150)
        y -= 160

    # Image result with heatmap
    if diagnosis_record.get('image_result') and diagnosis_record['image_result'].get('overlay_b64'):
        overlay_b64 = diagnosis_record['image_result']['overlay_b64']
        overlay_img = base64.b64decode(overlay_b64)
        overlay_io = io.BytesIO(overlay_img)
        c.drawImage(ImageReader(overlay_io), 50, y-200, width=200, height=200)
        c.drawString(270, y-10, f"Image prediction: {diagnosis_record['image_result']['disease']} ({diagnosis_record['image_result']['confidence']:.2%})")
        y -= 220

    # QR code
    qr = qrcode.QRCode(version=1, box_size=3, border=2)
    qr.add_data(f"https://yourdomain.com/verify/{diagnosis_id}")
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    img_path = f"/tmp/qr_{diagnosis_id}.png"
    img.save(img_path)
    c.drawImage(img_path, width-100, height-100, width=50, height=50)
    os.remove(img_path)

    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(50, 30, "This report is generated by AI and should be reviewed by a medical professional.")
    c.save()
    return filename